### ISSUE TITLE
Questions for setup

### ISSUE THREAD

**Issue by ymatsunaga** [t-/amber-dyes#1]
Hi, thank you for the great work. I would like ask your help in the setup of my system [Alexa488-Cys-WW_domain-Cys-Aexa647].
1. What do the last three letters mean in PDB file name (e.g., C1R of A48_C1R.pdb)? I guess the fist letter corresponds to the residue name of protein, but have no idea about the last two letters. I'm wondering which one should I choose for my system. 
2. How can I attach the dye to a residue of protein? I can create coordinates using VMD or PyMOL, but how can I create a bond between the protein and the dye using pdb2gmx? Do I need to add an entry in specbond.dat file?

Thanks,
Yasuhiro

**Comment by t-** [comment]
1. The name C1R decodes the type of amino acid, linker and position in the protein. You can find example pdb files of the different labels in the PDB_structures folder.
   
   C1R decodes into: 
   C = CYS , L= LYS, B=artificial keto amino acid Depending on the vendor and dye, the structure of the linker may vary.  The number indicates differences in the linkers.
   R = regular, N = N-terminal, C= C-terminal
2. Using PyMol/VMD works just fine. We originally wrote a script to do this automatically, but found it difficult to make it work under all circumstances.
   
   pdb2gmx will assign the bond parameters automatically based on position in the pdb file and naming of the atoms in the residue. It should work out of the box and you can check in the [ BONDS ] section of the topology if the bond was assigned properly. No additions to the specbond.dat file should be required. However, do make sure to energy minimize your structure before running free md simulations. In our experience steep with a small step size works best. You might want to freeze the rest of the protein or place strong position restraints. 

Regarding your system: the WW domain is very small given the large R_0 value for the A488/A647 pair. We had problems with this issue in the past and the FRET efficiencies may become too high on average >0.95. Also the folding/unfolding kinetics of the WW domain might not be properly described in TIP3P and a more accurate model may be required. 

best,
T

**Comment by ymatsunaga** [comment]
Thank you very much your replies and comment. We will carefully consider the difficulties of our system you mentioned. Thanks to your replies, we've finished building step of our system, but may I ask another question?
1. Regarding force field: By default, the combination of AMBER99SB and AMBER-DYES is given in your repository. Can I use another combination, such as AMBER99SB-ILDN and AMBER-DYES? If yes, how can I do that? Can I just add lines with "; AMBER-DYES" to existing ITP files?

I understand that AMBER99SB may be well compatible with AMBER-DYES as suggested by tryptohpan calculation, but we want to use better force fields.

Thanks,
Yasuhiro

**Comment by t-** [comment]
I added the parameters to the amber99sb-ildn port from Gromacs 5.0, see commit https://github.com/t-/amber-dyes/commit/2a514c9ff4aca1d13743f1b3a04dc5f586c2d3f5 . Check out the master branch again and it should show up.

**Comment by ymatsunaga** [comment]
Thank you very much for adding amber99sb-ildn!!

Sorry for my late reply, but we've finally confirmed that our MD program can run with the amber99sb-ildn_dyes. Looking at the motions of the dyes and comparison with FRET data are very exciting for me.

Thanks again for all of your replies.
I will contact you again if problems happen.

Thanks,
Yasuhiro
